import React from 'react';
import { Modal, Form, Input, Select, InputNumber, Typography, FormInstance } from 'antd';
import { AuthUser } from '@/store/useAuthStore';

const { Text } = Typography;

interface ItemModalProps {
    open: boolean;
    onOk: () => void;
    onCancel: () => void;
    form: FormInstance<any>;
    editingData: any;
    customers: any[];
    user: AuthUser | null;
}

export default function ItemModal({ open, onOk, onCancel, form, editingData, customers, user }: ItemModalProps) {
    return (
        <Modal title={editingData ? "Edit Item" : "Tambah Item Baru"} open={open} onOk={onOk} onCancel={onCancel}>
            <Form form={form} layout="vertical" className="mt-4">
                <Form.Item label="Pemilik Barang (Customer)" name="customerId" rules={[{ required: true }]}>
                    <Select placeholder="Pilih Customer" disabled={!!user?.customerId}>
                        {customers.map(c => (
                            <Select.Option key={c.id} value={c.id}>{c.name}</Select.Option>
                        ))}
                    </Select>
                </Form.Item>
                <Form.Item label="Kode Item (SKU)" name="code" rules={[{ required: !!editingData }]}>
                    <Input placeholder="Auto-generated by System" disabled={!editingData} />
                </Form.Item>
                <Form.Item label="Nama Barang" name="name" rules={[{ required: true }]}>
                    <Input />
                </Form.Item>
                <div className="grid grid-cols-2 gap-4">
                    <Form.Item 
                        label="Base UOM (Satuan Terkecil)" 
                        name="uom" 
                        rules={[{ required: true }]}
                    >
                        <Select placeholder="Pilih Satuan">
                            <Select.Option value="PCS">PCS</Select.Option>
                            <Select.Option value="KGS">KGS</Select.Option>
                            <Select.Option value="BTL">BTL</Select.Option>
                            <Select.Option value="ROLL">ROLL</Select.Option>
                        </Select>
                    </Form.Item>
                    <Form.Item label="Kategori" name="category">
                        <Input placeholder="Misal: Makanan, Apparel" />
                    </Form.Item>
                </div>

                <div className="bg-gray-50 p-4 rounded-md border border-gray-100 mb-4">
                    <Text strong className="block mb-4 text-gray-700">Satuan Kemasan & Konversi</Text>
                    <div className="grid grid-cols-2 gap-4">
                        <Form.Item label="Satuan Kemasan (Parent UOM)" name="parentUom">
                            <Select placeholder="Pilih Kemasan" allowClear>
                                <Select.Option value="BOX">BOX</Select.Option>
                                <Select.Option value="CTN">CTN (Karton)</Select.Option>
                                <Select.Option value="PALLET">PALLET</Select.Option>
                            </Select>
                        </Form.Item>
                        <Form.Item label="Isi per Kemasan" name="conversion">
                            <InputNumber className="w-full" min={1} placeholder="Contoh: 40" />
                        </Form.Item>
                    </div>
                </div>

                <div className="bg-gray-50 p-4 rounded-md border border-gray-100 mb-4">
                    <Text strong className="block mb-4 text-gray-700">Dimensi & Berat</Text>
                    <div className="grid grid-cols-3 gap-4">
                        <Form.Item label="Panjang (cm)" name="length">
                            <InputNumber className="w-full" min={0} step={0.1} />
                        </Form.Item>
                        <Form.Item label="Lebar (cm)" name="width">
                            <InputNumber className="w-full" min={0} step={0.1} />
                        </Form.Item>
                        <Form.Item label="Tinggi (cm)" name="height">
                            <InputNumber className="w-full" min={0} step={0.1} />
                        </Form.Item>
                    </div>
                    <Form.Item label="Berat per Unit (kg)" name="weight">
                        <InputNumber className="w-full" min={0} step={0.1} />
                    </Form.Item>
                </div>
            </Form>
        </Modal>
    );
}
