import React from 'react';
import { Modal, Form, Input, DatePicker, Typography, FormInstance } from 'antd';

const { Text } = Typography;

interface CustomerModalProps {
    open: boolean;
    onOk: () => void;
    onCancel: () => void;
    form: FormInstance<any>;
    editingData: any;
}

export default function CustomerModal({ open, onOk, onCancel, form, editingData }: CustomerModalProps) {
    return (
        <Modal title={editingData ? "Edit Customer" : "Tambah Customer Baru"} open={open} onOk={onOk} onCancel={onCancel}>
            <Form form={form} layout="vertical" className="mt-4">
                <Form.Item label="Kode Customer" name="code" rules={[{ required: !!editingData }]}>
                    <Input placeholder="Auto-generated by System" disabled={!editingData} />
                </Form.Item>
                <Form.Item label="Nama Customer" name="name" rules={[{ required: true }]}>
                    <Input />
                </Form.Item>
                <Form.Item label="Contact Person" name="contactPerson" rules={[{ required: true }]}>
                    <Input />
                </Form.Item>
                <Form.Item label="Email" name="email" rules={[{ type: 'email' }]}>
                    <Input />
                </Form.Item>
                <Form.Item label="Nomor Telepon" name="phone">
                    <Input />
                </Form.Item>
                
                <div className="bg-gray-50 p-4 rounded-md border border-gray-100 mt-6 mb-4">
                    <Text strong className="block mb-4 text-gray-700">Informasi Kontrak Penyimpanan</Text>
                    <div className="grid grid-cols-2 gap-4">
                        <Form.Item label="Tanggal Mulai Kontrak" name="contractStartDate">
                            <DatePicker className="w-full" format="YYYY-MM-DD" />
                        </Form.Item>
                        <Form.Item label="Tanggal Berakhir Kontrak" name="contractEndDate">
                            <DatePicker className="w-full" format="YYYY-MM-DD" />
                        </Form.Item>
                    </div>
                    <Form.Item label="Dokumen Kontrak (URL/Path)" name="contractDocument">
                        <Input placeholder="https://..." />
                    </Form.Item>
                </div>
            </Form>
        </Modal>
    );
}
